### ISSUE TITLE
ParaView-4.1.0

### ISSUE THREAD

**Issue by ColinB07** [pablo-benito/SOWFA-installation#1]
[logmakePV.txt](https://github.com/pablo-benito/SOWFA-installation/files/4230614/logmakePV.txt)

Hi Pablo,

I'm trying to install SOWFA on Ubuntu 18.04 through your steps. However, I have an issue to install Paraview-4.1.0 in the third party. Here attached the log. 
May you have some advises to tackle this?

Thank you very much,
Best regards
Colin

**Comment by pablo-benito** [comment]
Uf, nowadays compiling this (old!) version of Paraview from sources is useless.. 
You can go to the parawiew website and download the lastest version, already compiled for Linux. [https://www.paraview.org/download/](https://www.paraview.org/download/)
 It also has native support for opening OpenFOAM cases, you just  need to create an empty file, named` <<whateverYouLike>>.foam`,  inside the folder of your OpenFOAM case

**Comment by ColinB07** [comment]
Alright! Thank you very much, I'll try again this way.
