### ISSUE TITLE
make error when installing OpenFOAM

### ISSUE THREAD

**Issue by OMGTaylor0814** [pablo-benito/SOWFA-installation#10]
![8) QY}QWCVITH13O8BJSB9G](https://user-images.githubusercontent.com/78580228/231499456-f333b9bd-0566-4ab6-b9fe-39798124c628.png)
I met a problem when installing SOWFA-OpenFOAM which following your installation. I can't handle this so I hope you could help me.
it seems that some files could not find in /usr/lib/ld and I find these files are needed in SOWFA installation, where could I download them?

Best Regards,
Juniu.Wang

**Comment by OMGTaylor0814** [comment]
Hi Pablo Benito Cia

Thanks for your kindest help! my system version is 20.04 , and GCC version is 9.4.0

Although I really want to find errors myself and make corrections myself, unfortunately, my understanding of Ubuntu system and compilation is very shallow. If you are convenient, please help check the log.txt I exported. And I have found that you mentioned the statement "Warning" many times. I can't change the system I used for the time being, so I have to trouble you, I am looking forward to your reply.
[log.txt](https://github.com/pablo-benito/SOWFA-installation/files/11219994/log.txt)

Best regards,
Junius

**Comment by pablo-benito** [comment]
Yep, the error comes with the version of gcc, it is too _modern_ and considers invalid that code:

```
In file included from fields/fvPatchFields/derived/oscillatingFixedValue/oscillatingFixedValueFvPatchFields.H:29,
                 from fields/fvPatchFields/derived/oscillatingFixedValue/oscillatingFixedValueFvPatchFields.C:26:
fields/fvPatchFields/derived/oscillatingFixedValue/oscillatingFixedValueFvPatchField.H: In member function ‘Foam::scalar Foam::oscillatingFixedValueFvPatchField<Type>::amplitude() const’:
fields/fvPatchFields/derived/oscillatingFixedValue/oscillatingFixedValueFvPatchField.H:216:24: error: cannot convert ‘const Foam::autoPtr<Foam::DataEntry<double> >’ to ‘Foam::scalar’ {aka ‘double’} in return
  216 |                 return amplitude_;
      |                        ^~~~~~~~~~

```

Unfortunately the SOWFA code is unmaintained, and it requires this old version of OpenFOAM, that in turn requires an old version of the OS. I don't see any other workaround.. 

Options:
 - Install Ubuntu 18.04 and repeat the compilation process
 - Keep Ubuntu 20.04 but install a older version of the compilers:
  
  ```bash
  sudo apt install gcc-7 g++-7 
  ```
  and then tell your system that we have 2 possible compiler versions:

  ```
  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 20
  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 20
  sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 10
  sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 10
  ```

 After that, the default compiler version will be 7.5.0. 
 Then start from the beginning: Remove the OpenFOAM folder as it can contain files compiled with the other compiler and can cause problems. Then download again the code and try to recompile. 

 Hope it helps

**Comment by OMGTaylor0814** [comment]
Yes! Under your guidance, no error was reported again, but I don't know if the installation was successful, because there are no other hints.
I am very sorry that I may still need your help. During the last step of installing SOWFA, I encountered some fatal errors. After I checked twice, I probably simplified the following error log content. 

```
Building with OpenFOAM-2.4.x
'/home/junius/SOWFA/lib/linux64GccDPOpt/libSOWFAincompressibleLESModels.so' is up to date.
'/home/junius/SOWFA/lib/linux64GccDPOpt/libSOWFATurbineModelsStandard.so' is up to date.
OPENFAST_DIR is set to '/home/junius/software/OpenFAST/install'. Attempting to compile OpenFAST interface.
SOURCE=horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/triSurface/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/finiteVolume/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/meshTools/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/turbulenceModels -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/turbulenceModels/LES/LESdeltas/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/turbulenceModels/LES/LESfilters/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/transportModels -DOMPI_SKIP_MPICXX -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include -pthread -I/home/junius/software/OpenFAST/install/include -I/usr/lib/x86_64-linux-gnu/hdf5/serial/include -IlnInclude -I. -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/OpenFOAM/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/horizontalAxisWindTurbinesALMOpenFAST.o
In file included from horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.C:36:0:
horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.H:68:10 fatal error: OpenFAST.H: No such file or directory
 #include "OpenFAST.H"
          ^~~~~~~~~~~~
compilation terminated.
make: *** [horizontalAxisWindTurbinesALMOpenFAST/horizontalAxisWindTurbinesALMOpenFAST.dep:683: Make/linux64GccDPOpt/horizontalAxisWindTurbinesALMOpenFAST.o] Error 1
'/home/junius/SOWFA/lib/linux64GccDPOpt/libSOWFAsampling.so' is up to date.
'/home/junius/SOWFA/lib/linux64GccDPOpt/libSOWFAfileFormats.so' is up to date.
'/home/junius/SOWFA/lib/linux64GccDPOpt/libSOWFAfiniteVolume.so' is up to date.
'/home/junius/SOWFA/lib/linux64GccDPOpt/libSOWFAutilityFunctionObjects.so' is up to date.
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/setFieldsABL' is up to date.
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/ABLSolver' is up to date.
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/ABLTerrainSolver' is up to date.
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/windPlantSolver.ALM' is up to date.
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/windPlantSolver.ALMAdvanced' is up to date.
OPENFAST_DIR is set to '/home/junius/software/OpenFAST/install'. Attempting to compile OpenFAST windPlant solver.
SOURCE=windPlantSolver.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/turbulenceModels/incompressible/turbulenceModel -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/transportModels -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/transportModels/incompressible/singlePhaseTransportModel -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/finiteVolume/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/meshTools/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/fvOptions/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/sampling/lnInclude -I/home/junius/SOWFA/src/turbineModels/turbineModelsOpenFAST/lnInclude -DOMPI_SKIP_MPICXX -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include -pthread -I/home/junius/software/OpenFAST/install/include -I./interpolate2D -I/usr/lib/x86_64-linux-gnu/hdf5/serial/include/ -IlnInclude -I. -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/OpenFOAM/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/windPlantSolver.o
In file included from windPlantSolver.C:63:0:
/home/junius/SOWFA/src/turbineModels/turbineModelsOpenFAST/lnInclude/horizontalAxisWindTurbinesALMOpenFAST.H:68:10: fatal error: OpenFAST.H: No such file or directory
 #include "OpenFAST.H"
          ^~~~~~~~~~~~
compilation terminated.
make: *** [windPlantSolver.dep:725: Make/linux64GccDPOpt/windPlantSolver.o] Error 1
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/windPlantSolver.ADM' is up to date.
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/pisoFoamTurbine.ALM' is up to date.
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/pisoFoamTurbine.ALMAdvanced' is up to date.
OPENFAST_DIR is set to '/home/junius/software/OpenFAST/install'. Attempting to compile OpenFAST pisoFoam solver.
SOURCE=pisoFoamTurbine.C ;  g++ -m64 -Dlinux64 -DWM_DP -Wall -Wextra -Wno-unused-parameter -Wold-style-cast -Wnon-virtual-dtor -O3  -DNoRepository -ftemplate-depth-100 -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/turbulenceModels/incompressible/turbulenceModel -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/transportModels -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/transportModels/incompressible/singlePhaseTransportModel -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/finiteVolume/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/meshTools/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/fvOptions/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/sampling/lnInclude -I/home/junius/SOWFA/src/turbineModels/turbineModelsOpenFAST/lnInclude -DOMPI_SKIP_MPICXX -I/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -I/usr/lib/x86_64-linux-gnu/openmpi/include -pthread -I/home/junius/software/OpenFAST/install/include -I/usr/lib/x86_64-linux-gnu/hdf5/serial/include -IlnInclude -I. -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/OpenFOAM/lnInclude -I/home/junius/OpenFOAM/OpenFOAM-2.4.x/src/OSspecific/POSIX/lnInclude   -fPIC -c $SOURCE -o Make/linux64GccDPOpt/pisoFoamTurbine.o
In file included from pisoFoamTurbine.C:38:0:
/home/junius/SOWFA/src/turbineModels/turbineModelsOpenFAST/lnInclude/horizontalAxisWindTurbinesALMOpenFAST.H:68:10: fatal error: OpenFAST.H: No such file or directory
 #include "OpenFAST.H"
          ^~~~~~~~~~~~
compilation terminated.
make: *** [pisoFoamTurbine.dep:694: Make/linux64GccDPOpt/pisoFoamTurbine.o] Error 1
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/pisoFoamTurbine.ADM' is up to date.
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/turbineTestHarness.ALM' is up to date.
make: '/home/junius/SOWFA/applications/bin/linux64GccDPOpt/turbineTestHarness.ALMAdvanced' is up to date.
```


It seems that OpenFAST.H cannot be found., which results in a few fewer files about OpenFAST in the final generated file,as shown in the figure.
![image](https://user-images.githubusercontent.com/78580228/231826222-8ce997ef-ebef-4a30-91d4-ca6746262d49.png)
![image](https://user-images.githubusercontent.com/78580228/231826352-57b8ad06-bb27-4d45-a2e4-d1c3e6d5d560.png)

 I found the missing files through locate, but they do exist such as:
![image](https://user-images.githubusercontent.com/78580228/231826648-56dbea9f-146b-4ad1-9d2e-28d90aeca764.png)

How should I modify it? Did I make a mistake during the installation operation?

**Comment by OMGTaylor0814** [comment]
Hi Pablo Benito Cia，
Thanks for your help, sry to reply so late.
I tried to reinstall with your advice, I add extra dependencies in the SOWFA (namely -lfvwlib, -luaaerolib, -laeroacoustics and -lafinfolib) as you said. After that I met problems that:
![image](https://user-images.githubusercontent.com/78580228/233402987-e25af6dd-c1ce-4546-8622-eac6b336e77f.png)
so I locate it and find it in 
![image](https://user-images.githubusercontent.com/78580228/233403208-c332e1e8-45d2-4590-9ba2-704af4cbf88a.png)
so I make a soft link to the `/usr/lib/`
![image](https://user-images.githubusercontent.com/78580228/233403868-3a7c6baf-3b5a-4a03-8058-828f8aa49218.png)
But it is the .so file from the gcc 9 version, I don't know if it will affect, in fact, there has been no such error since.
Then I met an another error warning:
![image](https://user-images.githubusercontent.com/78580228/233404494-e1fcb655-2bb3-4591-98e3-2ef9c72ff72d.png)
I solve it in same way as lgfortran:

![image](https://user-images.githubusercontent.com/78580228/233404688-8c784332-281f-43a4-9e08-0cf389c046c6.png)
When i check the result , it seems one file missing `pisoFoamTurbine.ALMAdvancedOpenFAST `
![image](https://user-images.githubusercontent.com/78580228/233404913-7f837e05-3e8c-4384-a9d5-3fb9d0f5cd96.png)
![image](https://user-images.githubusercontent.com/78580228/233405170-40bf8ef4-3115-42ea-95af-bebbb40250a1.png)

nothing wrong in compile log , can you help me with it?
Best regards,
Junius

**Comment by pablo-benito** [comment]
I've checked the file:

```applications/solvers/incompressible/windEnergy/pisoFoamTurbine.ALMAdvancedOpenFAST/Make/files```

and as you can see, that program is now generated inside the `${FOAM_USER_APPBIN}` folder not in the `${SOWFA_DIR}/applications/bin/${WM_OPTIONS}` ...

**Comment by OMGTaylor0814** [comment]
Oh...
Seems i raised a foolish question...
Thanks your installation and help so much!
