### ISSUE TITLE
Installation Guide for SOWFA 6

### ISSUE THREAD

**Issue by danielgonro** [pablo-benito/SOWFA-installation#6]
Hi there.
I´m trying to install the SOWFA-6 version but the information in the git-hub is very confuse. For example,   the readme file it says to use only the OpenFOAM 6 version but in the bash_profile it is declare the 2.4.0 version.
It will be very helpful a similar guideline for the SOWFA-6 version.

Thanks 

Daniel

**Comment by pablo-benito** [comment]
This is not an issue related with the content of  this repository... It's a request. The place for this, is the section 'Discussions'

Again, I'm not related with the SOWFA / NREL project. I did this guide on my spare time.. 
SOWFA - 6 guide? Never say never, but I have to find the time and the motivation to do it.. 

I close this now
