### ISSUE TITLE
SOWFA Error in logs mpirun: SIGPIPE detected on fd 13 - aborting

### ISSUE THREAD

**Issue by mojeedoyedeji** [pablo-benito/SOWFA-installation#8]
Hi Pablo,

Thanks for your help on this forum

I am having issues with running SOWFA, I get the following errors in the log file

[elpadriinno:14777] [[5448,0],0] ORTE_ERROR_LOG: The system limit on number of pipes a process can open was reached in file base/iof_base_setup.c at line 111
mpirun: SIGPIPE detected on fd 13 - aborting

**Comment by pablo-benito** [comment]
This error is not related with SOWFA but with OpenMPI itself... 
Basically it's telling you that your program is trying to open too many pipes (like network connections), or at least more than your local configuration imposes.. But this limit is normally really high. 

First you should check your MPI installation. Check it with a sample MPI program, that everything is working correctly. Then check the number of processes that you're using to launch SOWFA, probably is _too_ high..  The SOWFA examples are intended for the NREL supercomputing facilities (the examples on the SOWFA repository use 216 process!), not a regular laptop..
